Overhaul build system
gluster/anthill-heketi pull request #6
Opened 2018-12-14 18:24 UTC by jarrpa

This PR brings in a build system similar to what is found in the gluster-csi-driver repo, while still maintaining a Makefile for a bit of familiarity and "documentation by coding" of the scripts directory.

2018-12-15 10:10 UTC, obnoxxx requested changes
Generally a good improvement!

But apart from two concrete points inline (one typo and one question), some general questions I'd like to discuss:

* Why is it that specifically build stuff is moved from the Makefile into a script? Is it because golang is just not good for doing build require tracking with Makefiles? A makefile is usually there for (and good at!) more than just documentation and convenience. I don't fully understand why each make target should just call a script.

* I don't especially like the fact that various test scripts are put under `scripts/`. Those should go under `test/`. We have the same in the csi-driver, and the infra came from heketi via glusterd2. This was, btw, in the csi-driver repo first. I don't know why this has been confused by putting other test scripts into `scripts/`. This should be fixed in the cis-repo as well. I propose that we copy the test infra from csi-driver here and cleanly put test scripts under test.

2018-12-15 10:10 UTC, obnoxxx commented on Dockerfile
> +# The version of the driver (git describe --dirty --always --tags | sed 's/-/./2' | sed 's/-/./2')
driver --> operator?

2018-12-15 10:10 UTC, obnoxxx commented on Dockerfile
> +ARG version="(unknown)"
what's the thing with `"(unknown)"` here?

2018-12-15 10:10 UTC, obnoxxx commented on Dockerfile
> +ARG builddate="(unknown)"
dito

2018-12-15 16:50 UTC, jarrpa commented on Dockerfile
> +ARG version="(unknown)"
This is in case the Dockerfile is built without `--build-arg version`, there should be a default since it gets used later.

2018-12-15 16:51 UTC, jarrpa commented on Dockerfile
> +# The version of the driver (git describe --dirty --always --tags | sed 's/-/./2' | sed 's/-/./2')
Yup

2018-12-15 16:54 UTC, jarrpa commented
> * Why is it that specifically build stuff is moved from the Makefile into a script? Is it because golang is just not good for doing build require tracking with Makefiles? A makefile is usually there for (and good at!) more than just documentation and convenience. I don't fully understand why each make target should just call a script.

The scripts are all written to take various environment variables, and the Makefile just calls them with defaults. I wanted to leave the ability to run the scripts with non-defaults, as I use them sometimes in development.

> * I don't especially like the fact that various test scripts are put under `scripts/`. Those should go under `test/`. We have the same in the csi-driver, and the infra came from heketi via glusterd2. This was, btw, in the csi-driver repo first. I don't know why this has been confused by putting other test scripts into `scripts/`. This should be fixed in the cis-repo as well. I propose that we copy the test infra from csi-driver here and cleanly put test scripts under test.

Eh, sure. I just put them there because they're still scripts. :) I'll move 'em.

2018-12-15 17:22 UTC, jarrpa commented
@obnoxxx Commits updated.

2018-12-19 15:09 UTC, jarrpa commented
@obnoxxx Reabes, PTAL

2019-01-09 15:50 UTC, jarrpa commented
@obnoxxx Rebased and test passes. PTAL

2022-05-12 18:06 UTC, closed without merging